In Java, does the finally block gets cexcuted if we insert a return statement inside the try block of a try-catch-finally?
